### ISSUE TITLE
Leiningen has moved to Codeberg

### ISSUE THREAD

**Issue by marcfargas** [miorimmax/asdf-lein#1]
This plugin currently checks https://github.com/technomancy/leiningen for releases and downloads, but the repository states:

> The canonical repository for Leiningen is [on Codeberg](https://codeberg.org/leiningen/leiningen) but we maintain [a mirror on GitHub](https://github.com/technomancy/leiningen) for the time being in order to ease the transition. Please update your links and git remotes.

So, when the mirror is removed the plugin will fail!

https://github.com/miorimmax/asdf-lein/blob/a6572986254d86e8cf183a61c225ea2d5b51813b/bin/list-all#L3

**Comment by miorimmax** [comment]
Hey! Thanks for bringing this up! Somehow it was lost in my github inbox, but now with https://github.com/miorimmax/asdf-lein/commit/c403a85f7393dc7d035981614f07f9af2b580e7e it should pull the tags and the lein binary from Codeberg.
